name: Sync to Daily Report Hub v2.2 (Fixed)
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, closed]

# 週の開始日を制御する設定
env:
  WEEK_START_DAY: 1 # 週の開始日 (0=日曜日, 1=月曜日, 2=火曜日, 3=水曜日, 4=木曜日, 5=金曜日, 6=土曜日)
  AUTO_APPROVE: true # プルリクエストの自動承認 (true/false)
  AUTO_MERGE: true # プルリクエストの自動マージ (true/false)
  CREATE_PR: true # プルリクエストを作成するか直接プッシュするか (true/false)

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitHub CLI
        run: |
          gh --version
          echo "GitHub CLI is ready"

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Calculate week information
        run: ./.github/scripts/calculate-week-info.sh ${{ env.WEEK_START_DAY }}

      - name: Analyze Git activity
        run: ./.github/scripts/analyze-git-activity.sh

      - name: Generate Markdown reports
        run: ./.github/scripts/generate-markdown-reports.sh

      - name: Clone report hub and create structure
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          REPORT_HUB_REPO: ${{ vars.REPORT_HUB_REPO || 'Sunwood-ai-labsII/daily-report-hub' }}
        run: |
          # Git設定
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # GitHub CLI認証
          echo "$GITHUB_TOKEN" | gh auth login --with-token
          
          # 認証確認
          gh auth status

          # daily-report-hubをクローン
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${REPORT_HUB_REPO}.git daily-report-hub

      - name: Create Docusaurus structure
        run: ./.github/scripts/create-docusaurus-structure.sh

      - name: Sync to report hub with PR flow (GitHub CLI)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          REPORT_HUB_REPO: ${{ vars.REPORT_HUB_REPO || 'Sunwood-ai-labsII/daily-report-hub' }}
          AUTO_APPROVE: ${{ env.AUTO_APPROVE }}
          AUTO_MERGE: ${{ env.AUTO_MERGE }}
          CREATE_PR: ${{ env.CREATE_PR }}
        run: ./.github/scripts/sync-to-hub-gh.sh
